name: Static analysis
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"
      - name: Verify formatting
        run: |
          set -euo pipefail

          make fmt

          DIFF=$(git status --porcelain)

          if [ -n "$DIFF" ]; then
            echo "These files were modified:"
            echo
            echo "$DIFF"
            echo
            exit 1
          fi
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.4
